const bookCategory = [
  'Fiction',
  'Children',
  'Memoir',
  'Biography',
  'Nonfiction',
  'Classic',
  'Dystopian',
  'Programming',
  'Romance',
  'Aestheticism',
  'Morality',
  'Gothic',
  'Mystery',
  'Detective',
  'Crime',
  'Urban',
  'Action',
  'Fantasy',
  'Mythology',
  'Horror',
  'Vampire',
  'Revenge',
  'Historical',
  'Epic',
  'Psychological',
  'Thriller',
  'Drama',
  'Tragedy',
  'Adventure',
  'Satire',
  'Absurdist',
  'Magical',
  'Surrealism',
  'Literature',
  'Nature',
  'Animal',
  'Computer Science',
  'Game Development',
  'Data Science',
  'Sci-Fi',
  'Artificial Intelligence',
  'Software Engineering',
  'Machine Learning',
  'Sociology',
  'Algorithms',
  'Philosophy',
  'Self-Help',
  'Economics',
  'Politics',
  'History',
  'Religion',
  'Spirituality',
  'Education',
  'Humor',
  'Health',
  'Fitness',
  'Travel',
  'True Crime',
  'Young Adult',
  'Paranormal',
  'Graphic Novels',
  'Comics',
  'Poetry',
  'Essays',
  'Anthology',
  'Cooking',
  'DIY',
  'Crafts',
  'Gardening',
  'Science',
  'Astronomy',
  'Physics',
  'Chemistry',
  'Biology',
  'Mathematics',
  'Engineering',
  'Business',
  'Marketing',
  'Finance',
  'Leadership',
  'Productivity',
  'Psychology',
  'Cultural Studies',
  'Environmental Science',
  'Legal Studies',
  'Music',
  'Art',
  'Photography',
  'Theater',
  'Performing Arts',
  'Military',
  'War',
  'Sports',
  'Autobiography',
  'Western',
  'Travel Guides',
  'Parenting',
  'Home Improvement',
  'Personal Development',
  'Astrology',
  'Technology',
  'Startup',
  'Cybersecurity',
];

export default bookCategory;
